### ISSUE TITLE
Bug: Fight type selected by winner feature not working

### ISSUE THREAD

**Issue by khardikk** [hady68/Superhero-Battle-App#1]
When selecting a fighting type and clicking the "Fight" button, the winner is not displayed as expected. This issue is reproducible on both desktop and mobile devices.

Steps to Reproduce:

1. Select a fight type from the dropdown menu.
2. Click on the "Fight" button.
3. Observe that the winner is not displayed and the page is refreshing without any changes.

Expected Behavior:
When clicking on "Fight" button, the winner should be displayed based on the selected fight type.

Actual Behavior:
The winner is not displayed

**Comment by Aatyagi** [comment]
I'd like to work on it .

**Comment by khardikk** [comment]
Hey @Aatyagi  i would be happy to assign it to you! How much time do you think it would take you to fix the bug?

**Comment by Aatyagi** [comment]
Dear @hady68, thank you for assigning me this issue. 

I want to assure you that I will complete it by tomorrow at the latest. 

Regarding the display of the winner, I suggest the following approach: when the winner is determined, their image should be enlarged and highlighted with a prominent "Winner" heading displayed above it, while the image of the loser should be reduced in size and visually de-emphasized, to avoid confusion and help users easily distinguish between the two. This will provide a clear and professional way of displaying the results, and enhance the user experience. 

Please let me know if you have any further suggestions or requirements. Thank you.

**Comment by khardikk** [comment]
Okay, great sounds good I have assigned you the issue @Aatyagi

**Comment by Aatyagi** [comment]
> Okay, great sounds good I have assigned you the issue @Aatyagi 

@hady68 hey, so i have added the js required to select the winner according to the fight type selected . 
Only need to add in the css class to the containers when user clicks the fight button . 👍

**Comment by khardikk** [comment]
> > Okay, great sounds good I have assigned you the issue @Aatyagi 
> 
> @hady68 hey, so i have added the js required to select the winner according to the fight type selected . 
> Only need to add in the css class to the containers when the click the fight button . 👍

Okay that's great, looking forward to your PR.
Tip : please add the images of the changes made so that it's easier to follow.

**Comment by Aatyagi** [comment]
yeah sure and how do you want me to handle superheroes with the null values ?

done with the code just going to refactor it for easy readability.

**Comment by khardikk** [comment]
@Aatyagi  For the ones with NULL value I want the app to say please choose another player.

**Comment by Aatyagi** [comment]
@hady68 sorry for the delay it took more time than I expected. Actually, the code is done but I want to refactor it before I show it to you. You can expect it by tomorrow evening.

**Comment by khardikk** [comment]
@Aatyagi  Not a problem, it's good to see that you are spending time refactoring your code!

**Comment by Aatyagi** [comment]
@hady68 hey friend, so the changes are done. So where do you want me to add screenshots, the description right?

**Comment by khardikk** [comment]
> @hady68 hey friend, so the changes are done. So where do you want me to add screenshots, the description right?

Yes please add them there

**Comment by Aatyagi** [comment]
@hady68 friend, I'm not sure, but do you really need screenshots? I'm asking because there are at least 8-10 screenshots, and it may make the answer too lengthy and difficult to read. Additionally, it might be easier to compare on GitHub directly, but it's ultimately your choice.

**Comment by khardikk** [comment]
> @hady68 friend, I'm not sure, but do you really need screenshots? I'm asking because there are at least 8-10 screenshots, and it may make the answer too lengthy and difficult to read. Additionally, it might be easier to compare on GitHub directly, but it's ultimately your choice.

Just 2 - 3 screenshots would work -> showing the winner popup modal and what happens when you click on the fight button , just screens which shows the functionality works.
